### ISSUE TITLE
Where are the docs

### ISSUE THREAD

**Issue by yeetus-maximus** [RubixDev/rustmatica#1]

**Comment by RubixDev** [comment]
I sadly pretty much abandoned this project before having a first real version released and thus never ended up adding any docs. There are, however, two examples in the examples folder and some tests you could have a look at. Just so it at least is usable in its current state, I published a version 0.1.0 on crates.io now. I want to return to this project as soon as I find time and motivation

**Comment by yeetus-maximus** [comment]
k thx

**Comment by RubixDev** [comment]
And in case you have any further questions, feel free to ask here

**Comment by yeetus-maximus** [comment]
is there any reason for using fastnbt instead of hematite

**Comment by RubixDev** [comment]
Well it was the first one I found and it did what I needed. Also I contributed to it and added a `nbt!` macro and support for (de)serializing Minecraft's UUIDs as 128-bit integers. So unless there is a good reason to switch to hematite or quartz I will probably stay with fastnbt as I didn't have any problems with it yet.

**Comment by RubixDev** [comment]
I've now finally added some documentation: https://docs.rs/rustmatica/
